server:
  port: 8083

spring:
  http:
    multipart:
      max-file-size: 900MB
      max-request-size: 900MB
  jackson:
    default-property-inclusion: NON_NULL
    serialization:
      write-dates-as-timestamps: false
  datasource:
    url: ${mysql.url:jdbc:mysql://localhost/music_analyzer}
    username: root
    password: ${mysql.root-pwd:send08}
    driver-class-name: com.mysql.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5Dialect

security.jwt:
  expTime: 60 # measure in minutes
  refreshExpTime: 180
  tokenIssuer: plantcare.io
  tokenSigningKey: n5Ewr42JCF6m1qcHF8hk


analyzer-service:
  base-url: http://localhost:8084/api/v1/analyzer
  get-music-features: /musics/{id}/features
  get-time-series: /musics/{id}/time-series
  get-spectrogram: /musics/{id}/spectrogram