version: '2'
services:
  music-analyzer-service:
    build:
      context: ../
      dockerfile: docker/music-analyzer-service/Dockerfile
      args:
        setupfile: service/target/service-0.0.1-SNAPSHOT.jar
    image: music-analyzer-service:0.0.1-SNAPSHOT
    env_file: music-analyzer-service/music-analyzer-service.env
    networks:
      - music
    ports:
      - "8083:8083"
networks:
  music:
    driver: bridge
